name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting an issue. Please make sure to include as many details as possible to replicate the issue and, where possible, screenshots too. It will really help to speed up the fixing process.'
        pr-message: 'Thank you for submitting a Pull Request. It will be validated as soon as possible. Please make sure to include as many details as possible, describing what exactly has been done.'
